# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03e3ffe3378d80aa8db5f2a264a91fb1e7cf14d676df2510f0bf410f4613bc8b25e3a8e6589e69a251834a6df07cf987ec508e959362a9ef100a7b557fd08004

test:
  secret_key_base: bebf93057a7a37a777c1d90db853d8e578421223d22c09ebc8524f0b3eff670f10f8ed4cbe66ef57ce624ff99f7f2733717c264671bc3afdf5ece946c0a7f13c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
